# -*- mode: ruby -*-
# vi: set ft=ruby :

PROJECT_NAME = "MyLaravelHomestead"
API_VERSION  = "2"

Vagrant.configure(API_VERSION) do |config|
	config.vm.define PROJECT_NAME, primary: true do |config|
		config.vm.provider :virtualbox do |vb|
			vb.name = PROJECT_NAME
		end

		config.vm.box = "laravel/homestead"
		config.vm.network :forwarded_port, guest: 80, host: 8055
	end
end
